### PR TITLE
Onboard connector flow templates on ACEccMT (Epic3163)

### PR DESCRIPTION
**Pull request by shahminiaru**
The following changes will be made to the master branch - https://github.com/ot4i/app-connect-templates/tree/master
PFA, the xls with the detailed information.
[AppConnect-Templates_v3.xlsx](https://github.com/ot4i/app-connect-templates/files/10146931/AppConnect-Templates_v3.xlsx)

Tasks:
1. Remove 35 templates that are not applicable/valid (ref xls).
i. Delete the YAML files.
ii. Remove the .md instruction for the .yaml files.
iii. Remove the entries for the templates in the template-metadata.json file.

2. Add 25 + 5 templates from CP4i repository.
i. Upload the .yaml files.
ii. Create the .md instruction for all the 31 use cases/templates.
iii. Add the entries for all the use cases/ templates in the template-metadata.json file.

### CODE REVIEW

**Comment by shahminiaru** [comment]
Ref: https://github.ibm.com/Cloud-Integration/appconnect-planning/issues/3163

**Comment by shahminiaru** [comment]
Hi @AnimatIan 
I have completed the epic 3163 task with this PR.
Can you please help to review and merge the changes to the master on priority? 

I have done the following actions/tasks:

Remove 35 templates that are not applicable/valid (ref xls).
i. Deleted the YAML files.
ii. Removed the .md instruction for the .yaml files.
iii. Removed the entries for the templates in the template-metadata.json file.

Add 29 templates from CP4i repository.
i. Uploaded the .yaml files.
ii. Created the .md instruction for all the 31 use cases/templates.
iii. Added the entries for all the use cases/ templates in the template-metadata.json file.

cc @CamK

**Review by AnimatIan — APPROVED** [review]
Approving to get current changes into use, but some changes needed for the template "Sync Salesforce Leads between accounts and check and record state" perhaps as a follow on PR.

The template "Sync Salesforce Leads between accounts and check and record state" is listed in the template-metadata.json, but the files have been deleted from the resources and metadata folders.  The template is listed in the spreadsheet (v4.
There are files for a template "Sync leads between Salesforce accounts and send email with the sync result" (which might be the same template) but that does not appear in template-metadata.yaml.
I think that some cleanup is needed if the template should be available, or delete the entry in template-metadata.yaml(?)

**Comment by AnimatIan** [comment]
@shahminiaru @CamK 
My review notes added to the templates spreadsheet: 
[AppConnect-Templates_v4_ipl.xlsx](https://github.com/ot4i/app-connect-templates/files/10177624/AppConnect-Templates_v4_ipl.xlsx)

**Comment by shahminiaru** [comment]
Hi @AnimatIan, thank you for reviewing and merging the PR-https://github.com/ot4i/app-connect-templates/pull/269

I have gone through your Excel compilation and here are some of the answers for your comments:

I didn’t look into the existing templates that was already in the master repository, only looked into the newly uploaded templates from cp4i repo.
I do agree with your comments listed for enhancements (Review comments (nice to have improvements)).
Please let me know if you want me to take up this effort – I need to inform my team abt the effort/PW. 

As for your other comments:
1. For template: Create new contact in Acoustic Campaign when a new contact is added in Salesforce (Not IBM Watson Campaign (in spreadsheet))
SA} I have updated the title from IBM Watson Campaign to Acoustic Campaign. The connector is displayed as Acoustic Campaign.

 2. Execute a large volume read request for an Anaplan view and share the data as an attachment via Gmail
Ian] Shouldn't use "Execute" as this is against IBM word usage, and not a term that Anaplan use.
SA} Ok – Will update the title on my next upload of templates. So, we can add this update to that PR.

3. The duplicate templates?
I crossed checked again with the backup master and the current master branch.
i. Sync Leads between accounts and record state
We do no have this template/entries in the resource, markdown & template.metadata file. The same is confirmed with the newly updated master branch.
ii. Sync Salesforce Leads between accounts and check and record state
This template exist in resource, markdown & template.metadata file.
iii. Sync leads between Salesforce accounts and send email with the sync result
This template exist in resource, markdown & template.metadata file.

4. Use short URL link to IBM Docs instead of blog?
The reason I gave the blog links is because the scenarios are explained in the blogs. The IBM docs/how to guide doesn’t capture the scenarios, it describes more on the connection and object and operations.

REF: 
[AppConnect-Templates_v4_ipl_sa.xlsx](https://github.com/ot4i/app-connect-templates/files/10183953/AppConnect-Templates_v4_ipl_sa.xlsx)

[AppConnect-Templates_v4_updated_5Dec22.xlsx](https://github.com/ot4i/app-connect-templates/files/10183960/AppConnect-Templates_v4_updated_5Dec22.xlsx)


cc @CamK @Deepak-Ayilliath

**Comment by AnimatIan** [comment]
@shahminiaru Thanks
I was not sure what the intention was for the templates, so did not make a fix that I could see.
The template "Sync Salesforce Leads between accounts and check and record state" does not appear in the gallery.  I think that is because its yaml file has the wrong "name" value:
`name: Sync Leads between accounts and record state`
That should match the filename without ".yaml", see [the guidelines](https://github.ibm.com/Cloud-Integration/appconnect-wiki/wiki/Authoring-App-Connect-templates#2-update-the-metadata-file), so be
`name: Sync Salesforce Leads between accounts and check and record state`
I think that with that fix, the template will appear in the gallery.

**Pull request merged**
