### PR TITLE
Salesforce event shahmini master

### PR DESCRIPTION
**Pull request by shahminiaru**
Salesforce event use cases

### CODE REVIEW

**Comment by shahminiaru** [comment]
Uploaded 2 use cases for Salesforce event:
Scenario 1 Platform event messages are published by publishers and are delivered in real-time to subscribers.
There are two parts to this scenario:
- Create a platform event in Salesforce whenever a product is created or updated in Microsoft Dynamics 365 for Sales
- Send a Gmail message when a platform event is triggered

Ref: https://github.ibm.com/Cloud-Integration/loopback-connector-salesforceevent/issues/473

**Comment by shahminiaru** [comment]
Scenario 2 Salesforce leads details are created or updated in Insightly and Amazon DynamoDB when a lead is either created or updated in Salesforce
There are two parts to this scenario:
1.	Store lead details in Insightly and Amazon DynamoDB whenever a new lead is created in Salesforce.
2.	Store lead details in Insightly and Amazon DynamoDB whenever a lead is updated in Salesforce.

**Review by AnimatIan — CHANGES_REQUESTED** [review]
The links to the instructions in Github don't work.  I think that they need to start with https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/ before the _instructions.md filename.
Please change the links in the _instructions.md files.

_instructions MD files includes an HTML </br> tag.  Please replace this with markdown.
- Create a platform event in Salesforce whenever a product is created or updated in Microsoft Dynamics 365 for Sales
- Send a Gmail message when a platform event is triggered

For the Store lead details templates, should we consider using the Salesforce event "New or updated leads", or perhaps just mention that it could be used instead of 2 separate flows?

**Comment by shahminiaru** [comment]
Updated.
- updated to include https://github.com/ot4i/app-connect-templates/blob/master/resources/markdown/
- removed html tags

**Review by shahminiaru — COMMENTED** [review]
`For the Store lead details templates, should we consider using the Salesforce event "New or updated leads", or perhaps just mention that it could be used instead of 2 separate flows?`

Hi Ian, I have updated the title for the Store..yaml use cases. 

The way we have described it in the blog is with the two flows; the sequel scenario is the updated use case. Hence, thought of keeping these 2 flows as templates. Let me know if u think otherwise. I can speak to the team and update the flow accordingly.

Scenario 2: Salesforce leads details are created or updated in Insightly and Amazon DynamoDB when a lead is either created or updated in Salesforce

There are two parts to this scenario:
1.	Create lead in Insightly and store the details in Amazon DynamoDB whenever a new lead is created in Salesforce.
2.	Update lead in Insightly and store the updated details in Amazon DynamoDB whenever a lead is updated in Salesforce.

**Review by AnimatIan — DISMISSED** [review]

**Review by AnimatIan — APPROVED** [review]

**Pull request merged**
