### PR TITLE
Vishalgadhvi patch 1

### PR DESCRIPTION
**Pull request by vishalgadhvi**

### CODE REVIEW

**Review by vishalgadhvi — COMMENTED** [review]
can someone approve and merge it

**Review by meechiekitten — APPROVED** [review]
Hi @vishalgadhvi 

Is this PR for 2 templates?

**Please ensure that all the updates for a single template are included in one PR**. In that PR, we expect to see:

1. An update in the resources/template-metadata.json file
1. The Yaml file for the App Connect flow
1. An instructions MD file
1. Ensure that all the builds have passed before requesting a review

Refer to the instructions here - [Creating a new template](https://github.ibm.com/Cloud-Integration/appconnect-wiki/wiki/Authoring-App-Connect-templates#creating-a-new-template) or reach out to me if you have any questions.

**Comment by vishalgadhvi** [comment]
Yes actually this pr consisted of 2 templates and yes all the mentioned instructions regarding updating the metadata.json, committing the yaml and instructions_md file is all done. Do i have to create two separate PR for two templates?

**Comment by meechiekitten** [comment]
@vishalgadhvi I'll let this one pass however it makes it very difficult for us review. In future we'd like to see a single PR for one template. I can see that a few changes are required, I'll review the PR and update the issue with the required changes.

**Comment by vishalgadhvi** [comment]
Okay thank you, i will look into it and make the necessary changes.

**Review by meechiekitten — CHANGES_REQUESTED** [review]
Hi @vishalgadhvi 

The following updates are required:

- The name **of** the yaml and the name **in** the yaml need to match exactly. This needs to be done for both yamls.

- I suggest updating the `Sync new:updated issue from Jira to Salesforce.yaml` to `Sync updated issues from Jira to Salesforce`.

- The `updated issue from Jira to Salesforce_instructions.md` file needs to match the name of the corresponding yaml exactly.

- On line 1 in both markdown files, you refer to opening the github page but you do not include a link.

- In the `updated issue from Jira to Salesforce_instructions.md` file 
  - Template is spelled incorrectly on Line 9. 
  - New sentences must begin with a capital letter. 
  - Is line 8 & 9 one sentence? Why are they on separate lines?

In the template metadata file:
- Line 1255 - the name on this line must match the name of the yaml file

- Line 1256 - Please update this line to read `When a new issue is created in Jira, this flow will check to see if there is a matching case in Salesforce. Cases are matched by summary. If no matching case is found in Salesforce then it will create a new case in Salesforce.`

- Line 1265 - Please update this line to read `For every campaign member that is created in Salesforce this flow will create a campaign member in Google Sheets on a new row.`

- The summary field must match how the dashboard would phrase it, please check your capitalization.

- Line 1268 - please ensure that you are using the correct internal name.

Given the number of changes required so far, I think it will be better to create 2 PRs (one for each template) because I still need to test the flows in designer.

Thanks

**Comment by vishalgadhvi** [comment]
will create two new pull request and make the necessary changes as mentioned

**Comment by meechiekitten** [comment]
@vishalgadhvi Please add me as a reviewer to the 2 new ones when they're complete. Thanks

**Pull request closed without merging**
