### PR TITLE
Team 1 : New spreadsheet row in Google Sheets will send SMSmsg via Twilio

### PR DESCRIPTION
**Pull request by ArpithaSrinivas5**
Team 1

### CODE REVIEW

**Review by meechiekitten — CHANGES_REQUESTED** [review]
The name of the yaml file and the name on line 53 need to match. Please can you update one or the other. Thank you.

**Review by ArpithaSrinivas5 — COMMENTED** [review]
I have renamed yml and name field in the yml. Please review and merge the code.

**Review by meechiekitten — COMMENTED** [review]
Hi @ArpithaSrinivas5 

Please close this PR and any PRs and branches that are associated with it that have not yet been merged. 

**Please ensure that all the updates for a single template are included in one PR**. In that PR, we expect to see:

1. An update in the `resources/template-metadata.json` file
1. The Yaml file for the App Connect flow
1. An instructions MD file
1. Ensure that all the builds have passed before requesting a review

Refer to the instructions here - [Creating a new template](https://github.ibm.com/Cloud-Integration/appconnect-wiki/wiki/Authoring-App-Connect-templates#creating-a-new-template) or reach out to me if you have any questions.

Thank you

**Comment by Deepak-Ayilliath** [comment]
Closing this PR as it's outdated. Please raise a new PR if required. Thanks!

**Pull request closed without merging**
