### PR TITLE
Cam k patch 6

### PR DESCRIPTION
**Pull request by CamK**
Hi Fiona, Chethan provided this YAML file, so I've created a draft template.  SAP Concur doesn't work in demo yet, so I've not been able to test it, so please could you test it when it's working in demo.  It's due in push 72, so please don't merge until then.  Thank you!

### CODE REVIEW

**Comment by feejaydee** [comment]
Will do @CamK

**Comment by apendrich** [comment]
@CamK Do you know if this is still needed?

**Comment by CamK** [comment]
@apendrich I'd say yes, as the connector was published.  It'll need testing, as I couldn't test it at the time because it wasn't working in demo, so I'll add it to my list to do at some point.

**Comment by Deepak-Ayilliath** [comment]
Closing this PR as it's no longer valid.

**Pull request closed without merging**
